### ISSUE TITLE
Battleground Timers

### ISSUE THREAD

**Issue by Noob1e** [Zidras/DBM-Warmane#6] opened 2021-07-09 17:56 UTC
Battleground timers often do not work or miscalculate time.

**Comment by Zidras** [comment] 2021-07-10 18:48
Can you specify which timers and which bg, so I can check?

**Comment by Noob1e** [comment] 2021-07-12 17:58
Hi. I don't know if it was bugged because of another addon but now it looks fine. Sorry for wasting your time.

**Comment by Zidras** [comment] 2021-07-13 17:01
No problem at all. Keep an eye on the issue, if you notice it again in a BG, do let me know which bg it was and which timer(s)/announce it was. A video with the problem would speed up the troubleshooting process tremendously

**Comment by Noob1e** [comment] 2021-07-15 19:10
I couldn't record a video but have some SS this time.

1) Someone attacked to Lumber Mill but timer didn't start.
![4](https://user-images.githubusercontent.com/27544010/125843752-3d3af152-51e4-4d17-b9d2-46f0e336b704.jpg)

2) Alliance attacked to Lumber Mill while Horde was trying to control it. But the timer didn't change.
![1](https://user-images.githubusercontent.com/27544010/125843458-bdf93aad-8fb0-49b4-bf4f-597077021f23.jpg)

3) Someone attacked to Farm but timer didn't start.
![2](https://user-images.githubusercontent.com/27544010/125843550-a5ab4cd5-b4dc-4e0a-8328-daf418f1b63a.jpg)

4) Again, Alliance attacked to Lumber Mill while Horde was trying to control it. But the timer didn't change.
![3-1](https://user-images.githubusercontent.com/27544010/125843632-81bdcc97-4a66-49b1-b607-d2163a5e06cb.jpg)
![3-2](https://user-images.githubusercontent.com/27544010/125843641-d8bded4f-1af4-49d6-9adf-fe483753ab41.jpg)

**Comment by Zidras** [comment] 2021-07-15 19:46
@Noob1e when you first opened the ticket, it was also arathin?

**Comment by Noob1e** [comment] 2021-07-15 20:56
Yep. Arathi Basin and Alterac Valley.

**Comment by Zidras** [comment] 2021-07-16 20:43
I checked the code and everything looks identical as retail. Since this is a PVP issue, there's not much I can do in my test server so I depend solely on VODs with right and wrong behaviour.

**Comment by Noob1e** [comment] 2021-07-17 09:57
Today I got into AV again but couldn't see any timer at all.
I was using Ayaro1's DBM before yours and iirc BG timers were working fine with it. I'll leave the link down below and hope it can help you to solve the problem.

https://github.com/Ayaro1/DBM_Warmane_Icecrown

**Comment by Zidras** [comment] 2021-07-17 10:04
Yeah I checked like 3 different DBMs, code is the same. I will have to go to a BG myself and test, but I'm currently not available to play, hence my request for vods :)

**Comment by Gescht** [comment] 2021-07-19 23:29
Is crossfaction pvp enabled on the server you had the issues with?

**Comment by Zidras** [comment] 2021-07-22 16:05
@Noob1e please check the above question, and also confirm if 4.52 dbm bugs too (other reports confirm this as being a warmane issue)

**Comment by Noob1e** [comment] 2021-07-22 19:29
@Gescht Yes, it's enabled on the server. Icecrown-Warmane.

@Zidras I just had time to check it out today. It was working in Alterac Valley, but it doesn't always bug. So I don't know if it will start bugging again.

**Comment by Zidras** [comment] 2021-07-22 19:48
@Noob1e it's very likely that this is being caused the cross-faction (if you or another player is a faction it's not supposed to be), or really Warmane just doing its usual "breaking working stuff" thing.
This will not be fixed anytime soon. To even begin to attempt trying to fix it, I need the following:
- VODs with Local Time
- Transcriptor logs of said VOD

**Comment by napnapnapnap** [comment] 2021-10-11 19:19
Hello, I have DBM-Warmane version 7.07.

I just did a 26 minute Arathi BG with lots of capping/defense etc. I've recorded the whole BG and logged with Transcriptor. After review of the video I found 0 errors with timers so either this got fixed by retail update or the issue is with mercenary mode.

**Comment by Zidras** [comment] 2021-10-11 19:21
Thanks for checking Nap

**Closed** 2021-12-13 19:43 UTC
Labels: bug, help wanted, question
